copy Browser.java from frameworks/base/core/java/android/provider to src/com/android/external/
#	new file:  src/com/android/external/Browser.java

java.lang.SecurityException: Permission Denial: reading
com.android.browser.provider.BrowserProvider2 uri
content://com.android.browser/history from pid=4668, uid=10089 requires
com.android.browser.permission.READ_HISTORY_BOOKMARKS